site_name: dna_api
site_description: An API that stores genes and show stats of it
repo_url: https://github.com/affonsobrian/dna-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/affonsobrian">affonsobrian</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
    - DNA: 'api/dna.md'
    - Status: 'api/stats.md'
