# Generated by Django 3.2.7 on 2021-09-11 20:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DNA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dna",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=6), size=None
                    ),
                ),
                ("is_mutant", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Statuts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_mutant_dna", models.PositiveBigIntegerField(default=0)),
                ("count_human_dna", models.PositiveBigIntegerField(default=0)),
                ("ratio", models.FloatField(default=1)),
            ],
        ),
    ]
